### ISSUE TITLE
Training details for refinement and upscaling

### ISSUE THREAD

**Issue by hxy-123-coder** [saiboxx/chexray-diffusion#3]
Thanks to your great work! But I still confuse on how to train Step 3(Refinement and upscaling using a super-resolution diffusion process).which config file does it use or is there another way to train it?

**Comment by saiboxx** [comment]
Hi @hxy-123-coder,

Thanks for the inquiry!
You're right to be confused, as this repository does not contain the training procedure for the super-resolution model.

The code for this is located in an extra repository.
I just set everything public: [Here!](https://github.com/saiboxx/diffusion-pytorch)

You will find a [script](https://github.com/saiboxx/diffusion-pytorch/blob/main/scripts/03_train_sr3_ddp.py) that reproduces the super-resolution model used in`Cheff`.

The basis of the current `Cheff` repository is the original LDM repository, which did not implement SR3. However, at the time of doing the project, for me it was a more dedicated solution to do a from scratch implementation of SR3 instead of trying to integrate it into the LDM framework.
In the new repository I tried to make everything as barebones (only plain torch) and easy-to-read as possible.

The original plan was to develop the new repo into a fully fledged framework, but then the hype towards Stable Diffusion kicked off and with the `diffusers` library my tiny project became obsolete within a few weeks ;).

I hope I could give you the information you need.
If you have more questions, please let me know.

Cheers,
Tobias

**Comment by hxy-123-coder** [comment]
Thanks for your reply! I will have a try.



At 2023-08-10 16:38:28, "Tobias Weber" ***@***.***> wrote:

Hi @hxy-123-coder,

Thanks for the inquiry!
You're right to be confused, as this repository does not contain the training procedure for the super-resolution model.

The code for this is located in an extra repository.
I just set everything public: Here!

You will find a script that reproduces the super-resolution model used inCheff.

The basis of the current Cheff repository is the original LDM repository, which did not implement SR3. However, at the time of doing the project, for me it was a more dedicated solution to do a from scratch implementation of SR3 instead of trying to integrate it into the LDM framework.
In the new repository I tried to make everything as barebones (only plain torch) and easy-to-read as possible.

The original plan was to develop the new repo into a fully fledged framework, but then the hype towards Stable Diffusion kicked off and with the diffusers library my tiny project became obsolete within a few weeks ;).

I hope I could give you the information you need.
If you have more questions, please let me know.

Cheers,
Tobias
