### ISSUE TITLE
Error when training the Autoencoder

### ISSUE THREAD

**Issue by AmarHek** [saiboxx/chexray-diffusion#4]
Dear authors,
thank you for the great library! Unfortunately, I'm having some issues trying to run the training.

I am using a Ubuntu machine and have installed all necessary libraries using the requirements.txt.
Initially, I had the problem of "name 'trainer' is not defined", which seemed to be fixed after properly logging into wandb and activating GPU support.
Now however, I keep getting the error, that AutoEncoderKL has no attribute 'learning_rate'. Of course, I could simply add it, but a hotfix might cause even more problems and I think this should not happen in the first place.

I'd greatly appreciate your help!

Cheers,
Amar

**Comment by saiboxx** [comment]
Hi Amar,

thanks for the interest in our work. :)

As it seems, you ran into 4 separate issues at once.
The basis for the repository is the original LDM repo, which unfortunately is a bit cluttered and hard to understand sometimes.
However, I just dug into the code and fixed a few side effects that occurred when parsing arguments with [059ca87](https://github.com/saiboxx/chexray-diffusion/commit/059ca87c7faaee83f5356165ad4994381ba7db9d).

### 1. W&B Logger

Originally, I added the W&B Logger as a default and its still recommended to do so, as this makes tracking and inspecting images when training on a remote server a lot easier.
You can overwrite the default by adjusting the configuration `.yml` files.
For example adding:

```
lightning:
  <... other stuff ...>

  logger:
    target: pytorch_lightning.loggers.CSVLogger
    params:
      save_dir: logs

```

will use classic logging to a CSV file. Every logger in lightning should work, if you supply the correct path and params.
Note that logging images will be deactivated when not choosing the W&B logger.


### 2. Activating GPU Support

The training script will fail, if you do not specify the correct amount of GPUs. 8 GPUs is the default, paired with a DDP strategy.
For not using a GPU adjust the training config like:

```
lightning:
  <... other stuff ...>

  trainer:
    gpus: 0
    strategy: None
```

For using one GPU do:

```
lightning:
  <... other stuff ...>

  trainer:
    gpus: 1
    strategy: None
```

Unfortunately the base repo relies on an old version of lightning and thus, the trainer arguments may not be in line with the documentation of the current version.


### 3. 'trainer' is not defined

This happened due to a weird try/except construct. When an error (like failed instantiation of a W&B logger) occurs, a `finally` block is triggered, which tries to print information about the trainer. Logically, this does not work if the trainer was not instantiated before.
I added a small check to fix this issue.


### 4. AutoEncoderKL has no attribute 'learning_rate'

I apologize. It appears that this is indeed an error of myself, which occurred when preparing a few things for the publication. I removed LR scaling, but it seems that I removed setting a LR in general. Sorry!


Please let me know, if everything works as expected now. :)

Cheers,
Tobias

**Comment by AmarHek** [comment]
Hi Tobias,

Sorry for the delayed answer and thank you so much for the detailed instructions!
Good to know, that the learning rate issue wasn't on my end after all, I was slowly losing my mind over it xD But such a simple line deletion can easily happen :D

I'm actually fine using the wandb logger now, I just wanted to let you know that it can fail if you are not logged in after all.
You may want to look at the logger check again however, since the script fails if you do not have a logger specified in your config. And thank you so much for the learning rate fix, it works like a charm now! Well, aside from my CUDA out of memory issue, but that's a separate problem haha.

Have you considered upgrading to pytorch-lighning 2.0? I know that some of the configs are deprecated, but with the current setups newer GPUs such as the RTX3090 do not work (at least on my end) due to older cuda versions.

But for now the autoencoder training works! If I encounter any problems further down the road, I hope I can message you again. Also I'd be happy to work on this project alongside you, since it will be an important asset in my PhD thesis further down the road as well!

Cheers,
Amar
